server:
  port: 8443

  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: "secret"   # debe coincidir con la del paso PKCS#12
    key-store-type: PKCS12

  http2:
    enabled: true
